package com.crazyboy.mathexam.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.crazyboy.mathexam.mybatis.model.Question;
@Mapper
public interface QuestionMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    Question selectByPrimaryKey(Integer questionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    List<Question> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Question record);
    
    List<Question> selectByUnitId(Integer unitId);
    
    void modifyContentByPrimaryKey(@Param("questionId")Integer questionId, @Param("content")String content);
    
    void modifyOptionsByPrimaryKey(@Param("questionId") Integer questionId, @Param("options")String options);
    
    String selectOptionsByPrimaryKey(Integer questionId);
}