package com.crazyboy.mathexam.mybatis.dao;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.crazyboy.mathexam.mybatis.model.Unit;
@Mapper
public interface UnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated
     */
    int insert(Unit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated
     */
    Unit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated
     */
    List<Unit> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Unit record);
}