spring:
    datasource:
        name: mathtest
        url: jdbc:mysql://119.29.9.243:3306/mathtest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
        username: root
        password: crazyboy
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
      cache: false
    messages:
      basename: i18n.login
    resources:
      static-locations: classpath:/templates/, classpath:/static/*, classpath:/i18n/*
mybatis:
  mapper-locations: classpath:mappers/*.xml