package com.crazyboy.mathexam.mybatis.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Question {
    /**
     * Database Column Remarks:
     *   题目id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_id
     *
     * @mbggenerated
     */
    private Integer questionId;

    /**
     * Database Column Remarks:
     *   单元id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.unit_id
     *
     * @mbggenerated
     */
    private Integer unitId;

    /**
     * Database Column Remarks:
     *   正确答案
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.answer
     *
     * @mbggenerated
     */
    private String answer;

    /**
     * Database Column Remarks:
     *   题干
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * Database Column Remarks:
     *   选项，至少一个
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.options
     *
     * @mbggenerated
     */
    private String options;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_id
     *
     * @return the value of question.question_id
     *
     * @mbggenerated
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_id
     *
     * @param questionId the value for question.question_id
     *
     * @mbggenerated
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.unit_id
     *
     * @return the value of question.unit_id
     *
     * @mbggenerated
     */
    public Integer getUnitId() {
        return unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.unit_id
     *
     * @param unitId the value for question.unit_id
     *
     * @mbggenerated
     */
    public void setUnitId(Integer unitId) {
        this.unitId = unitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.answer
     *
     * @return the value of question.answer
     *
     * @mbggenerated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.answer
     *
     * @param answer the value for question.answer
     *
     * @mbggenerated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.content
     *
     * @return the value of question.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.content
     *
     * @param content the value for question.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.options
     *
     * @return the value of question.options
     *
     * @mbggenerated
     */
    public String getOptions() {
        return options;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.options
     *
     * @param options the value for question.options
     *
     * @mbggenerated
     */
    public void setOptions(String options) {
        this.options = options == null ? null : options.trim();
    }
}