package com.crazyboy.mathexam.mybatis.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table unit
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Unit {
    /**
     * Database Column Remarks:
     *   单元id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   单元主题
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.theme
     *
     * @mbggenerated
     */
    private String theme;

    /**
     * Database Column Remarks:
     *   该单元占总分数的比重
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.percent
     *
     * @mbggenerated
     */
    private Float percent;

    /**
     * Database Column Remarks:
     *   该单元最高成绩
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column unit.max_score
     *
     * @mbggenerated
     */
    private Integer maxScore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.id
     *
     * @return the value of unit.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.id
     *
     * @param id the value for unit.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.theme
     *
     * @return the value of unit.theme
     *
     * @mbggenerated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.theme
     *
     * @param theme the value for unit.theme
     *
     * @mbggenerated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.percent
     *
     * @return the value of unit.percent
     *
     * @mbggenerated
     */
    public Float getPercent() {
        return percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.percent
     *
     * @param percent the value for unit.percent
     *
     * @mbggenerated
     */
    public void setPercent(Float percent) {
        this.percent = percent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column unit.max_score
     *
     * @return the value of unit.max_score
     *
     * @mbggenerated
     */
    public Integer getMaxScore() {
        return maxScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column unit.max_score
     *
     * @param maxScore the value for unit.max_score
     *
     * @mbggenerated
     */
    public void setMaxScore(Integer maxScore) {
        this.maxScore = maxScore;
    }
}